stages:
  - test

pytest:
  stage: test
  #rules:
    # Only run tests when committed to develop branch
    #- if: '$CI_COMMIT_REF_NAME != "develop"'
    #  when: never
  image: "python:$VERSION"
  before_script:
    # needed for h5repack (usually installed on computing clusters)
    - apt-get update -qq && apt-get install -y -qq hdf5-tools
    - python -m pip install --upgrade pip
    # install also optional dependencies for testing
    - python -m pip install .[test,clplot]
  script:
    - python -V
    - pytest --junitxml=report.xml
  parallel:
    matrix:
      - VERSION: ['3.8', '3.9', '3.10', '3.11']
  artifacts:
    when: always
    reports:
      junit: report.xml